
function initializeSlider(element) {
    jQuery('#amazingslider-19').amazingslider({
        jsfolder: "http://amazingslider.com/wp-content/uploads/amazingslider/19/sliderengine/",
        width: 600,
        height: 300,
        watermarkstyle: "text",
        loadimageondemand: false,
        watermarktext: "griha.co.in",
        isresponsive: true,
        autoplayvideo: false,
        watermarkimage: "",
        pauseonmouseover: false,
        watermarktextcss: "font:12px Arial,Tahoma,Helvetica,sans-serif;color:#333;padding:2px 4px;-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;background-color:#fff;opacity:0.9;filter:alpha(opacity=90);",
        randomplay: false,
        showwatermark: false,
        watermarklinkcss: "text-decoration:none;font:12px Arial,Tahoma,Helvetica,sans-serif;color:#333;",
        slideinterval: 5000,
        watermarktarget: "_blank",
        watermarkpositioncss: "display:block;position:absolute;top:4px;left:4px;",
        watermarklink: "",
        transitiononfirstslide: false,
        loop: 0,
        autoplay: true,
        navplayvideoimage: "play-32-32-0.png",
        navpreviewheight: 60,
        timerheight: 2,
        skin: "Navigator",
        textautohide: false,
        addgooglefonts: true,
        navshowplaypause: true,
        navshowplayvideo: false,
        navbuttonradius: 0,
        navpreviewposition: "top",
        navradius: 0,
        showshadow: false,
        navfeaturedarrowimagewidth: 16,
        navpreviewwidth: 120,
        googlefonts: "Inder",
        textpositionmarginright: 24,
        bordercolor: "#ffffff",
        navthumbnavigationarrowimagewidth: 32,
        navthumbtitlehovercss: "text-decoration:underline;",
        arrowwidth: 32,
        navmargin: 16,
        texteffecteasing: "easeOutCubic",
        texteffect: "slide",
        navspacing: 8,
        navarrowimage: "navarrows-28-28-0.png",
        ribbonimage: "ribbon_topleft-0.png",
        navwidth: 24,
        navheight: 24,
        timeropacity: 0.6,
        navthumbnavigationarrowimage: "carouselarrows-32-32-0.png",
        navpreviewbordercolor: "#ffffff",
        ribbonposition: "topleft",
        navthumbdescriptioncss: "display:block;position:relative;padding:2px 4px;text-align:left;font:normal 12px Arial,Helvetica,sans-serif;color:#333;",
        arrowstyle: "always",
        navthumbtitleheight: 20,
        textpositionmargintop: 24,
        navswitchonmouseover: false,
        playvideoimage: "playvideo-64-64-0.png",
        arrowimage: "arrows-32-32-2.png",
        textstyle: "dynamic",
        playvideoimageheight: 64,
        navfonthighlightcolor: "#666666",
        showbackgroundimage: false,
        navpreviewborder: 4,
        navdirection: "horizontal",
        navbuttonshowbgimage: true,
        navbuttonbgimage: "navbuttonbgimage-28-28-0.png",
        navthumbnavigationarrowimageheight: 32,
        textbgcss: "display:block; position:absolute; top:0px; left:0px; width:100%; height:100%; background-color:#fff; -webkit-border-radius: 2px; -moz-border-radius: 2px; border-radius: 2px; opacity:0.7; filter:alpha(opacity=70);",
        shadowcolor: "#aaaaaa",
        navborder: 4,
        bottomshadowimagewidth: 110,
        showtimer: true,
        navshowpreview: true,
        navpreviewarrowheight: 8,
        navfeaturedarrowimage: "featuredarrow-16-8-0.png",
        showribbon: false,
        navfeaturedarrowimageheight: 8,
        navstyle: "bullets",
        textpositionmarginleft: 24,
        descriptioncss: "display:block; position:relative; font:14px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#333;",
        navplaypauseimage: "navplaypause-28-28-0.png",
        backgroundimagetop: -10,
        timercolor: "#ffffff",
        navfontsize: 12,
        navhighlightcolor: "#333333",
        navimage: "bullet-24-24-5.png",
        navbuttoncolor: "#999999",
        navshowarrow: true,
        navshowfeaturedarrow: false,
        titlecss: "display:block; position:relative; font: 16px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#000;",
        ribbonimagey: 0,
        ribbonimagex: 0,
        shadowsize: 5,
        arrowhideonmouseleave: 1000,
        navopacity: 0.8,
        backgroundimagewidth: 120,
        navcolor: "#999999",
        navthumbtitlewidth: 120,
        playvideoimagewidth: 64,
        arrowheight: 32,
        arrowmargin: -48,
        texteffectduration: 1000,
        bottomshadowimage: "bottomshadow-110-95-2.png",
        border: 6,
        timerposition: "bottom",
        navfontcolor: "#333333",
        navthumbnavigationstyle: "arrow",
        borderradius: 0,
        navbuttonhighlightcolor: "#333333",
        textpositionstatic: "bottom",
        navthumbstyle: "imageonly",
        textcss: "display:block; padding:8px 16px; text-align:left; ",
        navbordercolor: "#ffffff",
        navpreviewarrowimage: "previewarrow-16-8-0.png",
        showbottomshadow: true,
        backgroundimage: "",
        navposition: "bottom",
        navpreviewarrowwidth: 16,
        bottomshadowimagetop: 95,
        textpositiondynamic: "bottomleft",
        navshowbuttons: false,
        navthumbtitlecss: "display:block;position:relative;padding:2px 4px;text-align:left;font:bold 14px Arial,Helvetica,sans-serif;color:#333;",
        textpositionmarginbottom: 24,
        slide: {
            duration: 1000,
            easing: "easeOutCubic",
            checked: true
        },
        transition: "slide"
    });
}